name: magic_invest
description: "Your wallet, like magic!"
publish_to: "none"
version: 0.1.1

environment:
  sdk: ^3.6.1

dependencies:
  auto_injector: ^2.0.5
  flutter:
    sdk: flutter

  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.20.2
  json_annotation: ^4.9.0
  json_serializable: ^6.9.0
  result_dart: ^2.0.0

  abelliz_essentials:
    path: "../abelliz_essentials"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  flutter_launcher_icons: ^0.14.3
  hive_generator: ^2.0.1
  build_runner: ^2.4.14
  freezed: ^2.5.7
  freezed_annotation: ^2.4.4

flutter:
  uses-material-design: true
